version: '3.8'

services:
  pg:
    image: public.ecr.aws/docker/library/postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - pg-data:/var/lib/postgresql/data

  go-microservice:
    image: janobono/go-microservice:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Bratislava
      - SERVER_PORT=8080
      - DB_HOST=pg
      - DB_USER=app
      - DB_PASSWORD=app
      - DB_NAME=app
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - pg

volumes:
  pg-data:
